package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import model.Team;

public class TeamRepository {
private Connection connection;
	
	private String createTableSql = "CREATE TABLE team("
			+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
			+ "name VARCHAR(20),"
			+ "country VARCHAR(20),"
			+ "players_id INT"
			+ ")";
	
	private Statement createTable;
	
	
	private String insertSql = "INSERT INTO team(name,country,players_id) VALUES(?,?,?)";
	private String deleteSql = "DELETE FROM team WHERE id = ?";
	private String updateSql = "UPDATE team set name=?,country=?, players_id=? WHERE id=?";
	private String selectByIdSql = "SELECT * FROM team WHERE id=?";
	private String selectAllSql = "SELECT * FROM team";
	
	private PreparedStatement insert;
	private PreparedStatement delete;
	private PreparedStatement update;
	private PreparedStatement selectById;
	private PreparedStatement selectAll;
	
	public TeamRepository(Connection connection) {
		this.connection = connection;
		
		try {
			createTable = connection.createStatement();
			
			boolean tableExists = false;
			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			while(rs.next()){
				if(rs.getString("TABLE_NAME").equalsIgnoreCase("team")){
					tableExists=true;
					break;
				}
			}
			if(!tableExists)
			createTable.executeUpdate(createTableSql);
			insert = connection.prepareStatement(insertSql);
			delete = connection.prepareStatement(deleteSql);	
			update = connection.prepareStatement(updateSql);
			selectById = connection.prepareStatement(selectByIdSql);
			selectAll = connection.prepareStatement(selectAllSql);
			
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public Team get(int teamId){
		try{
			
			selectById.setInt(1, teamId);
			ResultSet rs = selectById.executeQuery();
			while(rs.next()){
				Team result = new Team();
				result.setId(teamId);
				result.setName(rs.getString("name"));
				result.setCountry(rs.getString("country"));
				result.setPlayers(rs.getInt("player_id")); /////////////////////////////////////////////////////////
				return result;
			}
		}
		catch(SQLException ex){
			ex.printStackTrace();
		}
		return null;
	}

	public List<Team> getAll(){
		try{
			List<Team> result = new ArrayList<Team>();
			ResultSet rs = selectAll.executeQuery();
			while(rs.next()){
				Team p = new Team();
				
				p.setId(rs.getInt("id"));
				p.setName(rs.getString("name"));
				p.setCountry(rs.getString("country"));
				p.setPlayers(rs.getPlayers().getId("player_id")); ////////////////////////////////////////////////////////////
				result.add(p);
			}
			return result;
		}
		catch(SQLException ex){
			ex.printStackTrace();
		}
		return null;
	}
	
	public void delete(Team p){
		try{
			delete.setInt(1, p.getId());
			delete.executeUpdate();
		}catch(SQLException ex){
			ex.printStackTrace();
		}
	}
	
	public void add(Team p){
		try{	
			insert.setString(1, p.getName());
			insert.setString(2, p.getCountry());
			insert.setInt(3, p.getPlayers().getId());
			insert.executeUpdate();
			
		}catch(SQLException ex){
			ex.printStackTrace();
		}
		
	}
	
	public void update(Team p){
		try{
			update.setString(1, p.getName());
			update.setString(2, p.getCountry());
			update.setInt(3, p.getPlayers().getId());
			update.setInt(4, p.getId());
			update.executeUpdate();
			
		}catch(SQLException ex){
			ex.printStackTrace();
		}
		
	}
}
